### ISSUE TITLE
Platform implementation not found

### ISSUE THREAD

**Issue by KWodarczyk** [carolzbnbr/OnScreenSizeMarkup#12]
**Describe the bug**
i get error 'Platform implementation not found' if i debug this on windows machine

![image](https://user-images.githubusercontent.com/5243438/222245095-09f1b85f-5170-4083-b0c9-afa82f0b78c3.png)

vs 2022 win 10

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by carolzbnbr** [comment]
Hello, 

It is not clear if you are using Xamarin Forms or Maui.

But either way it seems that you are not targeting neither iOS nor Android devices when running on debug mode.
Please, try to start up your project in debug mode using either iOS or Android using the library for Xamarin Forms or Maui, and get me back the results.

If i'm wrong with my assumptions, please, provide me some more details and also a small sample solution so I can try to reproduce your issue here.

Thanks

**Comment by KWodarczyk** [comment]
I am using Maui, not sure what you mean targeting ?  when you debug in Visual Studio you can select between different Os but also you can select "Windows Machine" as on picture attached. It works fine if select Android Emulator but if i select "Windows Machine" if throws run time error as in my prev. post.

![image](https://user-images.githubusercontent.com/5243438/222253577-96361d38-5ffd-451e-8076-76bc8e41ed6d.png)

**Comment by carolzbnbr** [comment]
The library is intended to categorize physical screen sizes (not window sizes). As most Windows apps runs on large screens (monitors of any size, larger than a tablet), all of the Windows Apps would be categorized as Extra Large, so it makes no sense to have a windows support.

**Comment by KWodarczyk** [comment]
How about  OnScreenSizeMarkup.Core ? do i needs this as well ?

Regarding support for iOS and Android, i understand your point, but perhaps it should not fail the app or the error should say that it only supports iOS and Android, also if this i going to be ported to Maui Community Toolkit how is this going to work cause Maui does support windows, and finally you know it's quite handy to quickly test your app on Windows for basic stuff so that you don't have to load emulator or have phone connected, so would be nice if this had some default behavior for windows.

**Comment by carolzbnbr** [comment]
`How about OnScreenSizeMarkup.Core ? do i needs this as well ?`

The core projects, contains only reusable/shared code, not specific/targeted to any platform.

`Regarding support for iOS and Android, i understand your point, but perhaps it should not fail the app or the error should say that it only supports iOS and Android...`

Actually exception is not being thrown on my code, but on MAUI's code, when MAUI realize that there is no support for a platform other than iOS and Android. 

'also if this i going to be ported to Maui Community Toolkit how is this going to work cause Maui does support windows'

You are right, on MCT it should work on Windows. But we don't know when it is going to happen, as I'm not having enough time to port following their coding standards and guidelines, and they are lacking of people to help. 

But let me help you, I understood your point about running on Windows for quick touchups... I will try to create a windows implementation that always returns ExtraLarge.

Give me some minutes...

:D

**Comment by carolzbnbr** [comment]
Just published a new nuget version: https://www.nuget.org/packages/OnScreenSizeMarkup.Maui/2.0.3 

It should be available in a few minutes. 

Also, I implemented a way to specify the default categorization you want for Windows.

So, on the App.cs's constructor, set property `DefaultScreenCategoryFallbackPlatform` to the screen size you want for Windows. The default is ExtraLarge.
```cs
   Manager.Current.DefaultScreenCategoryFallbackPlatform = ScreenCategories.ExtraLarge;
```

Hope this helps.

**Comment by KWodarczyk** [comment]
Wow you are a start

**Comment by KWodarczyk** [comment]
I pulled the latest version and still get same error am I doing something wrong ?

**Comment by carolzbnbr** [comment]
Well, sorry about that.

it is not a problem on your code, but on how the library (nuget) was compiled/packaged.

I don't have any Windows machine here, even virtual ones, only a Mac. So when Ibuild/pack thelibrary it doesn't generates the windows version of the library inside the nuget file (I didn't remember that when I pack the latest version that could help you).

So the Library repo's has the fix, but not the latest nuget.


As I said, I don't have Windows machine here, but as you do, if you really want, you could download the repo's code, and Pack the Nuget on your own machine, by using the Dotnet Pack command inside the project's folder.
 

That way it will create a nuget file with the windows's version of the library. 

We should have a CI that could to that here, but I don't have much free time to mess with CI, and also I'm not a DevOps-oriented person. So besides free time, I would need some help in order to do that.  

But, as I said, you could create the nuget on your own computer.

**Comment by carolzbnbr** [comment]
And of course, after pack the nuget, you would need to create a local nuget repo/source pointing to the path where the generated .nupkg file is.

**Comment by carolzbnbr** [comment]
I'm assuming this issue should be closed, but if you still have problems let me know.

**Comment by KWodarczyk** [comment]
Well not sure as the nuget for windows is not availabe yet ? I can't do it either.

**Comment by BeepBeepBopBop** [comment]
Hello,  I am trying to use the library but unfortunately as repported here it can not run on a Windows app. I read the discussion above and I was wondering if somebody had the chance to create a new nugget package available for windows, or another solution ? Thanks a lot for any input on this.
